### ISSUE TITLE
two side error

### ISSUE THREAD

**Issue by superowner** [synqark/Arktoon-Shaders#121]
Hello, developer, when I use Arktoon-Shaders‘s Fade shader, there will be problems with the edges of double-sided materials with transparent maps.Besides, this plugin works very well and I like it very much!
See:
https://wx3.sinaimg.cn/mw690/007Bgb15ly1g22fhy355nj30gk0glgva.jpg

**Comment by synqark** [comment]
Hello. 
Using fade and overlapping another polys in same mesh causes bad result. like that.
This problems is due to Unity rendering engine and fix this seems difficult. I'm sorry.
Please consider to use AlphaCutout variations.

Thanks

**Comment by synqark** [comment]
特に動きがないため終了
