### ISSUE TITLE
Arktoon Mobile?

### ISSUE THREAD

**Issue by KortyBoi** [synqark/Arktoon-Shaders#129]
I was just wondering if you could make a version of Artoon as a toon shader for mobile. Not just for the VRchat Quest version, but other mobile games. It doesn't have to have all the nice features as the DX11+ version, but a more advanced version (compared to the VRChat/Mobile/Toon Lite).

**Comment by synqark** [comment]
No plan for now. 
But I guess it seems good to make as Vulkan version of this.
